using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Nuke.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Nuke.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCryptoNukeConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public ESCryptoNukeConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NavMap.WallColor = Color.Red;
        NavMap.TileColor = Color.Black;
    }

    public void Update(EntityUid owner, ESCryptoNukeConsoleBuiState? state = null)
    {
        NavMap.MapUid = _entityManager.GetComponent<TransformComponent>(owner).GridUid;

        if (state != null)
        {
            NavMap.TrackedCoordinates = state.DiskLocations
                .Select(c => (_entityManager.GetCoordinates(c), (true, Color.White)))
                .ToDictionary();
        }
    }
}
